# Generated by Django 4.2.3 on 2024-11-24 15:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('FirmName', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('PhoneNum', models.CharField(help_text='Enter numbers only', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric values are allowed.')])),
            ],
        ),
    ]
